.TH "clr::caller" 3 "Thu Oct 3 2024" "Caller_docs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clr::caller
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <caller\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.RI "A string of arbitrary length\&. "
.ti -1c
.RI "std::string \fBnumber\fP"
.br
.RI "A string up to 16 characters long, which can include numbers and a '+' sign at the beginning\&. "
.ti -1c
.RI "size_t \fBlastcall\fP"
.br
.RI "An integer value corresponding to a timestamp in UNIXtime format\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "size_t clr::caller::lastcall"

.PP
An integer value corresponding to a timestamp in UNIXtime format\&. 
.SS "std::string clr::caller::name"

.PP
A string of arbitrary length\&. 
.SS "std::string clr::caller::number"

.PP
A string up to 16 characters long, which can include numbers and a '+' sign at the beginning\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Caller_docs from the source code\&.
